import { Video, Channel, Playlist } from './types';

export const SAMPLE_VIDEOS: Video[] = [
  {
    id: '37aF96j3p6Q',
    title: 'Bhide And Jethalal\'s Story | Taarak Mehta Ka Ooltah Chashmah | तारक मेहता | Ep 4556',
    channelId: 'sony-sab-official',
    channelTitle: 'Sony SAB',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_kX4yX_T4n_0B147K1=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '94.2M subscribers',
    duration: '20:08',
    durationSeconds: 1208,
    views: 3340000,
    likes: 47200,
    publishedAt: '9 months ago',
    thumbnail: 'https://i.ytimg.com/vi/37aF96j3p6Q/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=37aF96j3p6Q',
    category: 'Comedy',
    description: 'Click here to Subscribe to Sony SAB: https://www.youtube.com/user/sonysab\n\nBhide gets furious as Jethalal breaks the window glass of his house while playing cricket in Gokuldham society! Watch the hilarious fight unfold.',
    watchedProgress: 0,
    isFavorite: false,
    inWatchLater: false,
    comments: [
      {
        id: 'c1',
        author: 'Rahul Sharma',
        authorAvatar: 'https://ui-avatars.com/api/?name=Rahul+Sharma&background=ef4444&color=fff',
        text: 'Bhai mera gala dukh gaya hanste hanste itna hansa itna hansa gala dukh gaya bhai...',
        likes: 612,
        timeAgo: '9 months ago',
        isLiked: true,
      },
      {
        id: 'c2',
        author: 'Anjali Mehta',
        authorAvatar: 'https://ui-avatars.com/api/?name=Anjali+Mehta&background=3b82f6&color=fff',
        text: 'Jethalal and Bhide combination is timeless comedy 😂❤️',
        likes: 340,
        timeAgo: '8 months ago',
      },
      {
        id: 'c3',
        author: 'Dev Techie',
        authorAvatar: 'https://ui-avatars.com/api/?name=Dev+Techie&background=10b981&color=fff',
        text: 'Best privacy YouTube player! Fast and ad-free experience.',
        likes: 120,
        timeAgo: '2 weeks ago',
      }
    ]
  },
  {
    id: '0e3GPea1Tyg',
    title: '$456,000 Squid Game In Real Life!',
    channelId: 'mrbeast',
    channelTitle: 'MrBeast',
    channelAvatar: 'https://yt3.googleusercontent.com/fxGKYucJAVme-YzgnGQnr6nxo7o_1BvLqj4o2Wk=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '315M subscribers',
    duration: '25:41',
    durationSeconds: 1541,
    views: 642000000,
    likes: 17000000,
    publishedAt: '2 years ago',
    thumbnail: 'https://i.ytimg.com/vi/0e3GPea1Tyg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=0e3GPea1Tyg',
    category: 'Trending',
    description: 'I recreated every single set from Squid Game in real life and gave 456 people the chance to compete for $456,000!',
    watchedProgress: 0,
    isFavorite: true,
    inWatchLater: true
  },
  {
    id: 'jfKfPfyJRdk',
    title: 'lofi hip hop radio 📚 - beats to relax/study to',
    channelId: 'lofigirl',
    channelTitle: 'Lofi Girl',
    channelAvatar: 'https://yt3.googleusercontent.com/uG_A2u2-x1b5N8pP1wA4Bq=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '14.5M subscribers',
    duration: 'LIVE',
    durationSeconds: 3600,
    views: 89000000,
    likes: 7200000,
    publishedAt: 'Streaming live',
    thumbnail: 'https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
    category: 'Music',
    description: 'Peaceful lofi hip hop radio - beats to relax/study to. Streamed 24/7 without trackers.',
    isFavorite: true,
    inWatchLater: false,
  },
  {
    id: '9bZkp7q19f0',
    title: 'PSY - GANGNAM STYLE(강남스타일) M/V',
    channelId: 'officialpsy',
    channelTitle: 'officialpsy',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_k2Q9=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '18.2M subscribers',
    duration: '04:12',
    durationSeconds: 252,
    views: 5200000000,
    likes: 28000000,
    publishedAt: '11 years ago',
    thumbnail: 'https://i.ytimg.com/vi/9bZkp7q19f0/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    category: 'Music',
    description: 'PSY - GANGNAM STYLE(강남스타일) Official Music Video.',
    inWatchLater: true,
  },
  {
    id: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
    channelId: 'luisfonsi',
    channelTitle: 'Luis Fonsi',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_n8qP=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '31.4M subscribers',
    duration: '04:41',
    durationSeconds: 281,
    views: 8500000000,
    likes: 53000000,
    publishedAt: '7 years ago',
    thumbnail: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    category: 'Music',
    description: '“Despacito” disponible ya en todas las plataformas digitales.',
  },
  {
    id: 'fJ9rUzIMcZQ',
    title: 'Queen – Bohemian Rhapsody (Official Video Remastered)',
    channelId: 'queenofficial',
    channelTitle: 'Queen Official',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_m4_a=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '17.8M subscribers',
    duration: '05:59',
    durationSeconds: 359,
    views: 1700000000,
    likes: 12000000,
    publishedAt: '15 years ago',
    thumbnail: 'https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
    category: 'Music',
    description: 'Taken from A Night At The Opera, 1975. Click here to buy the DVD with the full story.',
  }
];

export const SAMPLE_CHANNELS: Channel[] = [
  {
    id: 'sony-sab-official',
    name: 'Sony SAB',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_kX4yX_T4n_0B147K1=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '94.2M subscribers',
    videoCount: 18500,
    isSubscribed: true,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'mrbeast',
    name: 'MrBeast',
    avatar: 'https://yt3.googleusercontent.com/fxGKYucJAVme-YzgnGQnr6nxo7o_1BvLqj4o2Wk=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '315M subscribers',
    videoCount: 820,
    isSubscribed: true,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'mkbhd',
    name: 'Marques Brownlee',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_mkbhd=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '19.4M subscribers',
    videoCount: 1680,
    isSubscribed: false,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'fireship',
    name: 'Fireship',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_fireship=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '3.4M subscribers',
    videoCount: 620,
    isSubscribed: false,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'veritasium',
    name: 'Veritasium',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_veritasium=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '16.8M subscribers',
    videoCount: 410,
    isSubscribed: false,
    verified: true,
    hasUnread: false,
  }
];

export const SAMPLE_PLAYLISTS: Playlist[] = [
  {
    id: 'favorites',
    title: 'Liked Videos',
    videoCount: 0,
    thumbnail: '',
    updatedAt: 'Recently',
    isSystem: true,
    videoIds: [],
  },
  {
    id: 'watch-later',
    title: 'Watch Later',
    videoCount: 0,
    thumbnail: '',
    updatedAt: 'Recently',
    isSystem: true,
    videoIds: [],
  }
];

