import { Video, Channel, Playlist } from './types';

export const SAMPLE_VIDEOS: Video[] = [
  {
    id: 'jfKfPfyJRdk',
    title: 'lofi hip hop radio 📚 - beats to relax/study to',
    channelId: 'lofigirl',
    channelTitle: 'Lofi Girl',
    channelAvatar: 'https://yt3.googleusercontent.com/uG_A2u2-x1b5N8pP1wA4Bq=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '14.5M subscribers',
    duration: 'LIVE',
    durationSeconds: 3600,
    views: 89000000,
    likes: 7200000,
    publishedAt: 'Streaming live',
    thumbnail: 'https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
    category: 'Music',
    description: 'Peaceful lofi hip hop radio - beats to relax/study to. Streamed 24/7 without trackers.',
    isFavorite: true,
    inWatchLater: false,
    isLive: true,
  },
  {
    id: 'dQw4w9WgXcQ',
    title: 'Rick Astley - Never Gonna Give You Up (Official Music Video)',
    channelId: 'rickastley',
    channelTitle: 'Rick Astley',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_nK5G8g=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '4.2M subscribers',
    duration: '3:33',
    durationSeconds: 213,
    views: 1540000000,
    likes: 17000000,
    publishedAt: '1 day ago',
    thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    category: 'Music',
    description: 'The official video for Never Gonna Give You Up by Rick Astley.',
    watchedProgress: 0,
    isFavorite: true,
    inWatchLater: true
  },
  {
    id: '0e3GPea1Tyg',
    title: '$456,000 Squid Game In Real Life!',
    channelId: 'mrbeast',
    channelTitle: 'MrBeast',
    channelAvatar: 'https://yt3.googleusercontent.com/fxGKYucJAVme-YzgnGQnr6nxo7o_1BvLqj4o2Wk=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '315M subscribers',
    duration: '25:41',
    durationSeconds: 1541,
    views: 642000000,
    likes: 17000000,
    publishedAt: '2 days ago',
    thumbnail: 'https://i.ytimg.com/vi/0e3GPea1Tyg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=0e3GPea1Tyg',
    category: 'Trending',
    description: 'I recreated every single set from Squid Game in real life and gave 456 people the chance to compete for $456,000!',
    watchedProgress: 0,
    isFavorite: false,
    inWatchLater: false
  },
  {
    id: '37aF96j3p6Q',
    title: 'Taarak Mehta Ka Ooltah Chashmah - Highlights & Best Moments | Sony SAB',
    channelId: 'sony-sab-official',
    channelTitle: 'Sony SAB',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_kX4yX_T4n_0B147K1=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '94.2M subscribers',
    duration: '20:08',
    durationSeconds: 1208,
    views: 3340000,
    likes: 47200,
    publishedAt: '3 days ago',
    thumbnail: 'https://i.ytimg.com/vi/37aF96j3p6Q/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=37aF96j3p6Q',
    category: 'Comedy',
    description: 'Taarak Mehta Ka Ooltah Chashmah comedy scenes on Sony SAB.',
    watchedProgress: 0,
    isFavorite: false,
    inWatchLater: false,
  },
  {
    id: '9bZkp7q19f0',
    title: 'PSY - GANGNAM STYLE(강남스타일) M/V',
    channelId: 'officialpsy',
    channelTitle: 'officialpsy',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_k2Q9=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '18.2M subscribers',
    duration: '04:12',
    durationSeconds: 252,
    views: 5200000000,
    likes: 28000000,
    publishedAt: '11 years ago',
    thumbnail: 'https://i.ytimg.com/vi/9bZkp7q19f0/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    category: 'Music',
    description: 'PSY - GANGNAM STYLE(강남스타일) Official Music Video.',
    inWatchLater: true,
  },
  {
    id: 'kJQP7kiw5Fk',
    title: 'Luis Fonsi - Despacito ft. Daddy Yankee',
    channelId: 'luisfonsi',
    channelTitle: 'Luis Fonsi',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_n8qP=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '31.4M subscribers',
    duration: '04:41',
    durationSeconds: 281,
    views: 8500000000,
    likes: 53000000,
    publishedAt: '7 years ago',
    thumbnail: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    category: 'Music',
    description: '“Despacito” disponible ya en todas las plataformas digitales.',
  },
  {
    id: 'fJ9rUzIMcZQ',
    title: 'Queen – Bohemian Rhapsody (Official Video Remastered)',
    channelId: 'queenofficial',
    channelTitle: 'Queen Official',
    channelAvatar: 'https://yt3.googleusercontent.com/ytc/AIdro_m4_a=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '17.8M subscribers',
    duration: '05:59',
    durationSeconds: 359,
    views: 1700000000,
    likes: 12000000,
    publishedAt: '15 years ago',
    thumbnail: 'https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ',
    category: 'Music',
    description: 'Taken from A Night At The Opera, 1975. Click here to buy the DVD with the full story.',
  }
];

export const SAMPLE_CHANNELS: Channel[] = [
  {
    id: 'sony-sab-official',
    name: 'Sony SAB',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_kX4yX_T4n_0B147K1=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '94.2M subscribers',
    videoCount: 18500,
    isSubscribed: true,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'mrbeast',
    name: 'MrBeast',
    avatar: 'https://yt3.googleusercontent.com/fxGKYucJAVme-YzgnGQnr6nxo7o_1BvLqj4o2Wk=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '315M subscribers',
    videoCount: 820,
    isSubscribed: true,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'mkbhd',
    name: 'Marques Brownlee',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_mkbhd=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '19.4M subscribers',
    videoCount: 1680,
    isSubscribed: false,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'fireship',
    name: 'Fireship',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_fireship=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '3.4M subscribers',
    videoCount: 620,
    isSubscribed: false,
    verified: true,
    hasUnread: false,
  },
  {
    id: 'veritasium',
    name: 'Veritasium',
    avatar: 'https://yt3.googleusercontent.com/ytc/AIdro_veritasium=s176-c-k-c0x00ffffff-no-rj',
    subscriberCount: '16.8M subscribers',
    videoCount: 410,
    isSubscribed: false,
    verified: true,
    hasUnread: false,
  }
];

export const SAMPLE_PLAYLISTS: Playlist[] = [
  {
    id: 'favorites',
    title: 'Liked Videos',
    videoCount: 0,
    thumbnail: '',
    updatedAt: 'Recently',
    isSystem: true,
    videoIds: [],
  },
  {
    id: 'watch-later',
    title: 'Watch Later',
    videoCount: 0,
    thumbnail: '',
    updatedAt: 'Recently',
    isSystem: true,
    videoIds: [],
  }
];

